
name: Scorecard
on:
  schedule: [{cron: '0 1 * * 1'}]
  push: {branches: [ main ]}
permissions: { security-events: write, actions: read, contents: read }
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: results.sarif }
